import { Router } from "https://deno.land/x/oak/mod.ts";
import { ObjectId } from "https://deno.land/x/mongo@v0.8.0/mod.ts";

import { getDb } from "../helpers/db_client.ts";

const router = new Router();

interface Todo {
  id?: string;
  text: string;
}

let todos: Todo[] = [];

// ctx object provides access to req and res
router.get("/todos", async (ctx) => {
  const todos = await getDb().collection("todos").find(); // { _id: ObjectId(), text: '...' }[]
  const transformedTodos = todos.map(
    (todo: { _id: ObjectId; text: string }) => {
      // $oid: property provided by Mongo module on documents it fetches from MongoDB that holds ID generated by MongoDB but in string format rather than ObjectId
      return { id: todo._id.$oid, text: todo.text };
    },
  );
  // Oak automatically sends back response; just need to set response body, and if it's set to an object, Oak will assume it should be in JSON format; automatically transforms it to JSON and sets appropriate response headers
  ctx.response.body = { todos: transformedTodos };
});

router.post("/todos", async (ctx) => {
  const result = ctx.request.body();
  const data = await result.value;

  const newTodo: Todo = {
    // id: new Date().toISOString(),
    text: data.text,
  };

  const id = await getDb().collection("todos").insertOne(newTodo);

  newTodo.id = id.$oid;

  ctx.response.body = { message: "Created todo!", todo: newTodo };
});

router.put("/todos/:todoId", async (ctx) => {
  const tid = ctx.params.todoId;
  const result = ctx.request.body();
  const data = await result.value;
  const todoIndex = todos.findIndex((todo) => {
    return todo.id === tid;
  });
  todos[todoIndex] = { id: todos[todoIndex].id, text: data.value.text };
  ctx.response.body = { message: "Updated todo" };
});

router.delete("/todos/:todoId", (ctx) => {
  const tid = ctx.params.todoId;
  todos = todos.filter((todo) => todo.id !== tid);
  ctx.response.body = { message: "Deleted todo" };
});

export default router;
